version: "3"

services:
  validator1:
    networks:
      sui-network:
        ipv4_address: 10.0.0.11
    image: mysten/sui-node:mainnet
    container_name: validator1
    hostname: validator1
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=info,sui_core=debug,sui_network=debug,sui_node=debug,narwhal=debug,narwhal-primary::helper=info,jsonrpsee=error
      - RPC_WORKER_THREAD=12
    volumes:
      - ./genesis/files/validator1-8080.yaml:/opt/sui/config/validator.yaml:ro
      - ./genesis/files/genesis.blob:/opt/sui/config/genesis.blob:ro
      - /tmp/sui/db1:/opt/sui/db:rw
    command:
      [
        "/usr/local/bin/sui-node",
        "--config-path",
        "/opt/sui/config/validator.yaml",
      ]
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "1g"
  fullnode1:
    networks:
      sui-network:
        ipv4_address: 10.0.0.12
    image: mysten/sui-node:mainnet
    hostname: fullnode1
    container_name: fullnode1
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=info,sui_core=debug,sui_network=debug,sui_node=debug,narwhal=debug,narwhal-primary::helper=info,jsonrpsee=error
      - RPC_WORKER_THREAD=12
    volumes:
      - ./genesis/static/fullnode.yaml:/opt/sui/config/fullnode.yaml:ro
      - ./genesis/files/genesis.blob:/opt/sui/config/genesis.blob:ro
      - /tmp/sui/db5:/opt/sui/db:rw
    command:
      [
        "/usr/local/bin/sui-node",
        "--config-path",
        "/opt/sui/config/fullnode.yaml",
      ]
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "1g"
  api:
    networks:
      sui-network:
        ipv4_address: 10.0.0.13
    image: abodur/sui-api:cc0813f549a3143d43e15f9176e9d4202eec5c70
    platform: linux/amd64
    container_name: api
    hostname: api
    ports:
      - 7777:7777
    depends_on: 
      - fullnode1

networks:
  sui-network:
    driver: bridge
    ipam:
      config:
      - subnet: 10.0.0.0/24
