version: '3'
services:
  network:
    image: abodur/sui-network:5aa7cc6408db1250e36da5fbc045b2904da8a14c
    platform: linux/amd64
    container_name: network
    ports:
      - 9123:9123
      - 9000:9000
  ui:
    image: abodur/sui-ui:5aa7cc6408db1250e36da5fbc045b2904da8a14c
    platform: linux/amd64
    container_name: ui
    ports:
      - 8080:80
    depends_on:
      - network
  api:
    image: abodur/sui-api:5aa7cc6408db1250e36da5fbc045b2904da8a14c
    platform: linux/amd64
    container_name: api
    ports:
      - 7777:7777
    depends_on:
      - network
networks:
  sui-network:
    driver: bridge
    ipam:
      config:
      - subnet: 10.0.0.0/24
   