version: '3'
services:
  network:
    image: abodur/sui-network:c7a01ece94be7c054824e8c7177a0074310f1ae2
    platform: linux/amd64
    container_name: network
    ports:
      - 9123:9123
      - 9000:9000
  ui:
    image: abodur/sui-ui:c7a01ece94be7c054824e8c7177a0074310f1ae2
    platform: linux/amd64
    container_name: ui
    ports:
      - 8080:80
    depends_on:
      - network
  api:
    image: abodur/sui-api:c7a01ece94be7c054824e8c7177a0074310f1ae2
    platform: linux/amd64
    container_name: api
    ports:
      - 7777:7777
    depends_on:
      - network