version: '3'
services:
  network:
    # networks:
    #   sui-network:
    #     ipv4_address: 10.0.0.11
    image: abodur/sui-network:3a47c187ee41bc3b0b5109c2e49bf4a947b3972f
    platform: linux/amd64
    container_name: network
    hostname: network
    ports:
      - 9123:9123
      - 8000:8000
  ui:
    image: abodur/sui-ui:3a47c187ee41bc3b0b5109c2e49bf4a947b3972f
    platform: linux/amd64
    container_name: ui
    hostname: ui
    ports:
      - 8080:80
    depends_on:
      - network
  api:
    # networks:
    #   sui-network:
    #     ipv4_address: 10.0.0.12
    image: abodur/sui-api:3a47c187ee41bc3b0b5109c2e49bf4a947b3972f
    platform: linux/amd64
    container_name: api
    hostname: api
    ports:
      - 7777:7777
    depends_on:
      - network
# networks:
#   sui-network:
#     driver: bridge
#     ipam:
#       config:
#       - subnet: 10.0.0.0/24
   