version: '3'
services:
  network:
    networks:
      sui-network:
        ipv4_address: 10.0.0.11
    image: abodur/sui-network:cdf542d9680d6edb42909700edcb0176482a8cf8
    platform: linux/amd64
    container_name: network
    hostname: network
    ports:
      - 9123:9123
      - 9000:9000
  ui:
    image: abodur/sui-ui:cdf542d9680d6edb42909700edcb0176482a8cf8
    platform: linux/amd64
    container_name: ui
    hostname: ui
    ports:
      - 8080:80
    depends_on:
      - network
  api:
    networks:
      sui-network:
        ipv4_address: 10.0.0.12
    image: abodur/sui-api:cdf542d9680d6edb42909700edcb0176482a8cf8
    platform: linux/amd64
    container_name: api
    hostname: api
    ports:
      - 7777:7777
    depends_on:
      - network
networks:
  sui-network:
    driver: bridge
    ipam:
      config:
      - subnet: 10.0.0.0/24
   