name: Build Docker Image

on:
  push:
  workflow_dispatch:

jobs:
  ui:
    uses: ./.github/workflows/builder.yaml
    with:
      component: ui
  api:
    uses: ./.github/workflows/builder.yaml
    with:
      component: api
  network:
    uses: ./.github/workflows/builder.yaml
    with:
      component: network