name: Build Docker Images for components [UI, API, Network]
on:
  push:
  workflow_dispatch:

jobs:
  ui:
    uses: ./.github/workflows/builder.yaml
    with:
      component: ui
    secrets: inherit
  api:
    uses: ./.github/workflows/builder.yaml
    with:
      component: api
    secrets: inherit
  network:
    uses: ./.github/workflows/builder.yaml
    with:
      component: network
    secrets: inherit