name: Build Docker Images for components [UI, API, Network]
on:
  push:
  workflow_dispatch:
    
jobs:
  ui:
    name: Build and push UI
    uses: ./.github/workflows/builder.yaml
    with:
      component: ui
    secrets: inherit
  api:
    name: Build and push API
    uses: ./.github/workflows/builder.yaml
    with:
      component: api
    secrets: inherit
  network:
    name: Build and push Network
    uses: ./.github/workflows/builder.yaml
    with:
      component: network
    secrets: inherit

  test:
    name: Test on Ubuntu
    needs: 
      - ui
      - api
      - network
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4
      # Check docker-compose is installed
      - name: Docker run
        working-directory: deployment
        run: docker-compose up -d --build
      - name: Print the logs
        working-directory: deployment
        # get logs for 30 seconds
        run: sleep 30 && docker-compose logs