name: Build Docker Image

on:
  push:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu
    steps:
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4
      # Set up QEMU
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Build and push
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./deployment/network.Dockerfile
          push: true
          tags: abodur/sui-init:${{ github.sha }}, abodur/sui-init:latest
  test:
    needs: build-and-push
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker run
        working-directory: deployment
        run: docker-compose up -d --build
      - name: Print the logs
        working-directory: deployment
        # get logs for 30 seconds
        run: sleep 30 && docker-compose logs
