name: Build/release

on: 
  push:
  workflow_dispatch:

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
      # move to ui directory
      - name: Move to UI directory
        run: cd ui
      # install dependencies
      - name: Install dependencies
        run: yarn install
      # build the app
      - name: Build the app
        run: yarn make
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          # Name of the artifact to upload.
          # Optional. Default is 'artifact'
          name: build
          # A file, directory or wildcard pattern that describes what to upload
          # Required.
          path: ui/out/*