name: SUI TEST
on:
  push:
  workflow_dispatch:
    
jobs:
  test:
    name: Test on Ubuntu
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      # checkout https://github.com/MystenLabs/sui/
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: MystenLabs/sui
          ref: releases/sui-v1.25.0-release
          # branch releases/sui-v1.24.0-release
      # install cargo
      - name: Install cargo
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          source $HOME/.cargo/env
          cargo --version
      # install SUI
      - name: Install SUI
        run: |
          cargo build --bin sui
      # install stress
      - name: Install stress
        working-directory: docker/stress
        run: docker build -t stress:testing --build-arg SUI_TOOLS_IMAGE_TAG=mainnet-v1.19.1 .
      # run compose
      - name: Docker run
        working-directory: docker/sui-network
        run: docker-compose up -d --build

